/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import exe.*;
import com.*;

import javax.swing.JOptionPane;
import java.awt.CardLayout;

/**
 *
 * @author userPC
 */
public class AdminView extends javax.swing.JFrame {
    int i = 0;
    private int Hasil = 0;
    /**
     * Creates new form AdminView
     */
    public void setName(){
        jLabel2.setText("No Inap");
        jLabel3.setText("ID Pasien");
        jLabel4.setText("ID Resepsionis");
        jLabel5.setText("ID Riwayat");
        jLabel6.setText("ID Kamar");
        jLabel8.setText("Tgl Inap");
    }
    
    public AdminView() {
        initComponents();
        VisualEffect(7);
        setName();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        resepsionisButton = new javax.swing.JButton();
        kamarButton = new javax.swing.JButton();
        pasienButton = new javax.swing.JButton();
        riwayatButton = new javax.swing.JButton();
        transkripButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        DeleteButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        AddButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(207, 207, 232));

        resepsionisButton.setText("Resepsionis");
        resepsionisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resepsionisButtonActionPerformed(evt);
            }
        });

        kamarButton.setText("Kamar");
        kamarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kamarButtonActionPerformed(evt);
            }
        });

        pasienButton.setText("Pasien");
        pasienButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasienButtonActionPerformed(evt);
            }
        });

        riwayatButton.setText("Riwayat Penyakit");
        riwayatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riwayatButtonActionPerformed(evt);
            }
        });

        transkripButton.setText("Transkrip");
        transkripButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transkripButtonActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(207, 207, 232));

        jLabel1.setText("ID");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        jLabel6.setText("jLabel6");

        jLabel7.setText("jLabel7");

        jLabel8.setText("jLabel8");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(jTextField2)
                    .addComponent(jTextField3)
                    .addComponent(jTextField4))
                .addGap(129, 129, 129)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(jTextField6)
                    .addComponent(jTextField7)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(resepsionisButton)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kamarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(riwayatButton))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pasienButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(transkripButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 925, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UpdateButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(DeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AddButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(AddButton)
                        .addGap(47, 47, 47)
                        .addComponent(UpdateButton)
                        .addGap(50, 50, 50)
                        .addComponent(DeleteButton))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(resepsionisButton)
                            .addComponent(kamarButton)
                            .addComponent(pasienButton))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(riwayatButton)
                            .addComponent(transkripButton))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void riwayatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riwayatButtonActionPerformed
        tableRiwayat();
        i = 1;
        VisualEffect(6);
        jLabel2.setText("Nama Penyakit");
        jLabel3.setText("Jenis Penyakit");
        jLabel8.setText("Waktu Penyakit");
    }//GEN-LAST:event_riwayatButtonActionPerformed

    private void resepsionisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resepsionisButtonActionPerformed
        tableResepsionis();
        i = 2;
        VisualEffect(5);
        jLabel2.setText("Nama");
        jLabel3.setText("Username");
        jLabel4.setText("Password");
        jLabel5.setText("Level");
    }//GEN-LAST:event_resepsionisButtonActionPerformed

    private void kamarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kamarButtonActionPerformed
        tableRuangan();
        i = 3;
        VisualEffect(4);
        jLabel2.setText("Tipe Kamar");
        jLabel3.setText("Staus Kamar");
        jLabel4.setText("Biaya Kamar");
    }//GEN-LAST:event_kamarButtonActionPerformed

    private void transkripButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transkripButtonActionPerformed
       tableTranskrip();
        i = 4;
        VisualEffect(7);
        setName();
    }//GEN-LAST:event_transkripButtonActionPerformed

    private void pasienButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasienButtonActionPerformed
        tablePasien();
        i = 5;
        VisualEffect(3);
        jLabel2.setText("Nama Pasien");
        jLabel2.setText("Tgl Lahir");
    }//GEN-LAST:event_pasienButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        switch(i){
            case 1:
                java.util.Date time3 = jDateChooser1.getDate();
                java.sql.Date Waktu = new java.sql.Date(time3.getTime());
                Riwayat newR = new Riwayat();
                ExecuteRiwayat exeR = new ExecuteRiwayat();
                newR.setId_riwayat(Integer.parseInt(jTextField1.getText()));
                newR.setNama_penyakit(jTextField2.getText());
                newR.setJenis_penyakit(jTextField3.getText());
                newR.setWaktu_penyakit(Waktu);
                
                Hasil = exeR.deleteRiwayat(newR);
                tableRiwayat();
                break;
            case 2:
                Resepsionis newResep = new Resepsionis();
                ExecuteResepsionis exeRes = new ExecuteResepsionis();
                newResep.setId_resepsionis(Integer.parseInt(jTextField1.getText()));
                newResep.setNama_resepsionis(jTextField2.getText());
                newResep.setUsername(jTextField3.getText());
                newResep.setPassword(jTextField4.getText());
                newResep.setLevel(jTextField5.getText());
                
                Hasil = exeRes.deleteResepsionis(newResep);
                tableResepsionis();
                break;
            case 3:
                Kamar newK = new Kamar();
                ExecuteKamar exeK = new ExecuteKamar();
                newK.setId_kamar(Integer.parseInt(jTextField1.getText()));
                newK.setTipe_kamar(jTextField2.getText());
                newK.setStatus_kamar(jTextField3.getText());
                newK.setHarga_kamar(Integer.parseInt(jTextField4.getText()));
                
                Hasil = exeK.deleteKamar(newK);
                tableRuangan();
                break;
            case 4:
                java.util.Date time4 = jDateChooser1.getDate();
                java.sql.Date Waktu2 = new java.sql.Date(time4.getTime());
                ExecutePasien ePasien = new ExecutePasien();
                ExecuteResepsionis eResep = new ExecuteResepsionis();
                ExecuteKamar eKamar = new ExecuteKamar();
                ExecuteRiwayat eRiwa = new ExecuteRiwayat();
                Transkrip newTra = new Transkrip();
                ExecuteTranskrip exeTra = new ExecuteTranskrip();
                newTra.setId_transkrip(Integer.parseInt(jTextField1.getText()));
                newTra.setNo_inap(jTextField2.getText());
                newTra.setTgl_inap(Waktu2);
                Pasien _pasien = ePasien.trackPasienID(jTextField3.getText());
                newTra.setPasien(_pasien);
                Resepsionis _resep = eResep.trackResepsionis(Integer.parseInt(jTextField4.getText()));
                newTra.setResepsionis(_resep);
                Kamar _kamar = eKamar.trackKamar(jTextField5.getText());
                newTra.setKamar(_kamar);
                Riwayat _riwayat = eRiwa.trackRiwayatID(jTextField6.getText());
                newTra.setRiwayat(_riwayat);
                
                
                Hasil = exeTra.deleteTranskrip(newTra);
                tableTranskrip();
                break;
            case 5:
                java.util.Date time5 = jDateChooser1.getDate();
                java.sql.Date Waktu3 = new java.sql.Date(time5.getTime());
                Pasien newPa = new Pasien();
                ExecutePasien pasi = new ExecutePasien();
                newPa.setId_pasien(Integer.parseInt(jTextField1.getText()));
                newPa.setNama_pasien(jTextField2.getText());
                newPa.setTgl_pasien(Waktu3);
                
                Hasil = pasi.deletePasien(newPa);
                tablePasien();
                break;
        }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        
        switch(i){
            case 1:
                java.util.Date time3 = jDateChooser1.getDate();
                java.sql.Date Waktu = new java.sql.Date(time3.getTime());
                Riwayat newR = new Riwayat();
                ExecuteRiwayat exeR = new ExecuteRiwayat();
                
                newR.setNama_penyakit(jTextField2.getText());
                newR.setJenis_penyakit(jTextField3.getText());
                newR.setWaktu_penyakit(Waktu);
                
                Hasil = exeR.insertRiwayat(newR);
                tableRiwayat();
                break;
            case 2:
                Resepsionis newResep = new Resepsionis();
                ExecuteResepsionis exeRes = new ExecuteResepsionis();
                
                newResep.setNama_resepsionis(jTextField2.getText());
                newResep.setUsername(jTextField3.getText());
                newResep.setPassword(jTextField4.getText());
                newResep.setLevel(jTextField5.getText());
                
                Hasil = exeRes.insertResepsionis(newResep);
                tableResepsionis();
                break;
            case 3:
                Kamar newK = new Kamar();
                ExecuteKamar exeK = new ExecuteKamar();
                
                newK.setTipe_kamar(jTextField2.getText());
                newK.setStatus_kamar(jTextField3.getText());
                newK.setHarga_kamar(Integer.parseInt(jTextField4.getText()));
                
                Hasil = exeK.insertKamar(newK);
                tableRuangan();
                break;
            case 4:
                java.util.Date time4 = jDateChooser1.getDate();
                java.sql.Date Waktu2 = new java.sql.Date(time4.getTime());
                ExecutePasien ePasien = new ExecutePasien();
                ExecuteResepsionis eResep = new ExecuteResepsionis();
                ExecuteKamar eKamar = new ExecuteKamar();
                ExecuteRiwayat eRiwa = new ExecuteRiwayat();
                Transkrip newTra = new Transkrip();
                ExecuteTranskrip exeTra = new ExecuteTranskrip();
                
                newTra.setNo_inap(jTextField2.getText());
                newTra.setTgl_inap(Waktu2);
                Pasien _pasien = ePasien.trackPasienID(jTextField3.getText());
                newTra.setPasien(_pasien);
                Resepsionis _resep = eResep.trackResepsionis(Integer.parseInt(jTextField4.getText()));
                newTra.setResepsionis(_resep);
                Kamar _kamar = eKamar.trackKamar(jTextField5.getText());
                newTra.setKamar(_kamar);
                Riwayat _riwayat = eRiwa.trackRiwayatID(jTextField6.getText());
                newTra.setRiwayat(_riwayat);
                
                
                Hasil = exeTra.insertTranskrip(newTra);
                tableTranskrip();
                break;
            case 5:
                java.util.Date time5 = jDateChooser1.getDate();
                java.sql.Date Waktu3 = new java.sql.Date(time5.getTime());
                Pasien newPa = new Pasien();
                ExecutePasien pasi = new ExecutePasien();
                
                newPa.setNama_pasien(jTextField2.getText());
                newPa.setTgl_pasien(Waktu3);
                
                Hasil = pasi.insertPasien(newPa);
                tablePasien();
                break;
        }
    }//GEN-LAST:event_AddButtonActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        switch(i){
            case 1:
                java.util.Date time3 = jDateChooser1.getDate();
                java.sql.Date Waktu = new java.sql.Date(time3.getTime());
                Riwayat newR = new Riwayat();
                ExecuteRiwayat exeR = new ExecuteRiwayat();
                newR.setId_riwayat(Integer.parseInt(jTextField1.getText()));
                newR.setNama_penyakit(jTextField2.getText());
                newR.setJenis_penyakit(jTextField3.getText());
                newR.setWaktu_penyakit(Waktu);
                
                Hasil = exeR.updateRiwayat(newR);
                tableRiwayat();
                break;
            case 2:
                Resepsionis newResep = new Resepsionis();
                ExecuteResepsionis exeRes = new ExecuteResepsionis();
                newResep.setId_resepsionis(Integer.parseInt(jTextField1.getText()));
                newResep.setNama_resepsionis(jTextField2.getText());
                newResep.setUsername(jTextField3.getText());
                newResep.setPassword(jTextField4.getText());
                newResep.setLevel(jTextField5.getText());
                
                Hasil = exeRes.updateResepsionis(newResep);
                tableResepsionis();
                break;
            case 3:
                Kamar newK = new Kamar();
                ExecuteKamar exeK = new ExecuteKamar();
                newK.setId_kamar(Integer.parseInt(jTextField1.getText()));
                newK.setTipe_kamar(jTextField2.getText());
                newK.setStatus_kamar(jTextField3.getText());
                newK.setHarga_kamar(Integer.parseInt(jTextField4.getText()));
                
                Hasil = exeK.updateKamar(newK);
                tableRuangan();
                break;
            case 4:
                java.util.Date time4 = jDateChooser1.getDate();
                java.sql.Date Waktu2 = new java.sql.Date(time4.getTime());
                ExecutePasien ePasien = new ExecutePasien();
                ExecuteResepsionis eResep = new ExecuteResepsionis();
                ExecuteKamar eKamar = new ExecuteKamar();
                ExecuteRiwayat eRiwa = new ExecuteRiwayat();
                Transkrip newTra = new Transkrip();
                ExecuteTranskrip exeTra = new ExecuteTranskrip();
                newTra.setId_transkrip(Integer.parseInt(jTextField1.getText()));
                newTra.setNo_inap(jTextField2.getText());
                newTra.setTgl_inap(Waktu2);
                Pasien _pasien = ePasien.trackPasienID(jTextField3.getText());
                newTra.setPasien(_pasien);
                Resepsionis _resep = eResep.trackResepsionis(Integer.parseInt(jTextField4.getText()));
                newTra.setResepsionis(_resep);
                Kamar _kamar = eKamar.trackKamar(jTextField5.getText());
                newTra.setKamar(_kamar);
                Riwayat _riwayat = eRiwa.trackRiwayatID(jTextField6.getText());
                newTra.setRiwayat(_riwayat);
                
                
                Hasil = exeTra.updateTranskrip(newTra);
                tableTranskrip();
                break;
            case 5:
                java.util.Date time5 = jDateChooser1.getDate();
                java.sql.Date Waktu3 = new java.sql.Date(time5.getTime());
                Pasien newPa = new Pasien();
                ExecutePasien pasi = new ExecutePasien();
                newPa.setId_pasien(Integer.parseInt(jTextField1.getText()));
                newPa.setNama_pasien(jTextField2.getText());
                newPa.setTgl_pasien(Waktu3);
                
                Hasil = pasi.updatePasien(newPa);
                tablePasien();
                break;
        }
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void VisualEffect(int baris){
        
        switch(baris){
            case 0:jLabel1.setVisible(false);
                jTextField1.setVisible(false);
                               
                jLabel2.setVisible(false);
                jTextField2.setVisible(false);
                
                jLabel3.setVisible(false);
                jTextField3.setVisible(false);
                 
                jLabel4.setVisible(false);
                jTextField4.setVisible(false);
                
                jLabel5.setVisible(false);
                jTextField5.setVisible(false);
                
                jLabel6.setVisible(false);
                jTextField6.setVisible(false);
                
                jLabel7.setVisible(false);
                jTextField7.setVisible(false);
                
                jLabel8.setVisible(false);
                jDateChooser1.setVisible(false);
                break;
            case 3:
                jLabel1.setVisible(true);
                jTextField1.setVisible(true);
                               
                jLabel2.setVisible(true);
                jTextField2.setVisible(true);
                
                jLabel3.setVisible(false);
                jTextField3.setVisible(false);
                 
                jLabel4.setVisible(false);
                jTextField4.setVisible(false);
                
                jLabel5.setVisible(false);
                jTextField5.setVisible(false);
                
                jLabel6.setVisible(false);
                jTextField6.setVisible(false);
                
                jLabel7.setVisible(false);
                jTextField7.setVisible(false);
                
                jLabel8.setVisible(true);
                jDateChooser1.setVisible(true);
                
                break;
            case 4:
                jLabel1.setVisible(true);
                jTextField1.setVisible(true);
                               
                jLabel2.setVisible(true);
                jTextField2.setVisible(true);
                
                jLabel3.setVisible(true);
                jTextField3.setVisible(true);
                 
                jLabel4.setVisible(true);
                jTextField4.setVisible(true);
                
                jLabel5.setVisible(false);
                jTextField5.setVisible(false);
                
                jLabel6.setVisible(false);
                jTextField6.setVisible(false);
                
                jLabel7.setVisible(false);
                jTextField7.setVisible(false);
                
                jLabel8.setVisible(false);
                jDateChooser1.setVisible(false);
                break;
            case 5:
                jLabel1.setVisible(true);
                jTextField1.setVisible(true);
                               
                jLabel2.setVisible(true);
                jTextField2.setVisible(true);
                
                jLabel3.setVisible(true);
                jTextField3.setVisible(true);
                 
                jLabel4.setVisible(true);
                jTextField4.setVisible(true);
                
                jLabel5.setVisible(true);
                jTextField5.setVisible(true);
                
                jLabel6.setVisible(false);
                jTextField6.setVisible(false);
                
                jLabel7.setVisible(false);
                jTextField7.setVisible(false);
                
                jLabel8.setVisible(false);
                jDateChooser1.setVisible(false);
                break;
            case 6:
                jLabel1.setVisible(true);
                jTextField1.setVisible(true);
                               
                jLabel2.setVisible(true);
                jTextField2.setVisible(true);
                
                jLabel3.setVisible(true);
                jTextField3.setVisible(true);
                 
                jLabel4.setVisible(false);
                jTextField4.setVisible(false);
                
                jLabel5.setVisible(false);
                jTextField5.setVisible(false);
                
                jLabel6.setVisible(false);
                jTextField6.setVisible(false);
                
                jLabel7.setVisible(false);
                jTextField7.setVisible(false);
                
                jLabel8.setVisible(true);
                jDateChooser1.setVisible(true);
                break;
            case 7:
                jLabel1.setVisible(true);
                jTextField1.setVisible(true);
                               
                jLabel2.setVisible(true);
                jTextField2.setVisible(true);
                
                jLabel3.setVisible(true);
                jTextField3.setVisible(true);
                 
                jLabel4.setVisible(true);
                jTextField4.setVisible(true);
                
                jLabel5.setVisible(true);
                jTextField5.setVisible(true);
                
                jLabel6.setVisible(true);
                jTextField6.setVisible(true);
                
                jLabel7.setVisible(false);
                jTextField7.setVisible(false);
                
                jLabel8.setVisible(true);
                jDateChooser1.setVisible(true);
                break;
        }
    }
    
    public void tablePasien(){
        ExecutePasien psen = new ExecutePasien();
        Object[][] myPasien = psen.listKamar();
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            myPasien,
            new String [] {
                "ID Pasien", "Nama Pasien", "Tanggal Lahir"
            }
        ));
    }
    
    public void tableResepsionis(){
        ExecuteResepsionis rsp = new ExecuteResepsionis();
        Object[][] myResepsionis = rsp.listResepsionis();
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            myResepsionis,
            new String [] {
                "ID", "Nama", "Usename", "Password", "Level"
            }
        ));
    }
    
    public void tableRuangan(){
        ExecuteKamar kmr = new ExecuteKamar();
        Object[][] myKamar = kmr.listKamar();
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            myKamar,
            new String [] {
                "ID Kamar", "Tipe Kamar", "Status Kamar" , "Biaya Kamar"
            }
        ));
    }
    
    public void tableTranskrip(){
        ExecuteTranskrip trns = new ExecuteTranskrip();
        Object[][] myTranskrip = trns.listAdminTranskrip();
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            myTranskrip,
            new String [] {
                "ID Transkrip", "No.Inap", "Tangga Inap" , "ID Pasien",
                "ID Resepsionis", "ID Riwayat", "ID Kamar"
            }
        ));
    }
    
    public void tableRiwayat(){
         ExecuteRiwayat rwt = new ExecuteRiwayat();
        Object[][] myRiwayat = rwt.listRiwayat();
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            myRiwayat,
            new String [] {
                "ID", "Nama Penyakit", "Jenis Penyakit" , "Waktu Penyakit"
                
            }
        ));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton UpdateButton;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JButton kamarButton;
    private javax.swing.JButton pasienButton;
    private javax.swing.JButton resepsionisButton;
    private javax.swing.JButton riwayatButton;
    private javax.swing.JButton transkripButton;
    // End of variables declaration//GEN-END:variables
}
